import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/animate.css',
                'resources/css/bootstrap.min.css',
                'resources/css/component.css',
                'resources/css/default.css',
                'resources/css/feature_post.css',
                'resources/css/flaticon.css',
                'resources/css/font-awesome.min.css',
                'resources/css/liner_icon.css',
                'resources/css/magnific-popup.css',
                'resources/css/nice-select.css',
                'resources/css/owl.carousel.min.css',
                'resources/css/post_style.css',
                'resources/css/search.css',
                'resources/css/slick.css',
                'resources/css/style.css',
                'resources/css/swiper.min.css',
                'resources/css/themify-icons.css',
                'resources/css/aos.css',
                'resources/js/classie.js',
                'resources/js/contact.js',
                'resources/js/custom.js',
                'resources/js/jquery.ajaxchimp.min.js',
                'resources/js/jquery.form.js',
                'resources/js/jquery.nice-select.min.js',
                'resources/js/jquery.validate.min.js',
                'resources/js/jquery-1.12.1.min.js',
                'resources/js/mail-script.js',
                'resources/js/popper.min.js',
                'resources/js/uisearch.js',
                'resources/sass/app.scss',
                'resources/js/app.js',
                'resources/js/bootstrap.min.js',
                'resources/dist/css/alt/adminlte.components.css',
                'resources/dist/css/alt/adminlte.components.min.css',
                'resources/dist/css/alt/adminlte.core.css',
                'resources/dist/css/alt/adminlte.extra-components.css',
                'resources/dist/css/alt/adminlte.light.css',
                'resources/dist/css/alt/adminlte.pages.css',
                'resources/dist/css/alt/adminlte.plugins.css',
                'resources/dist/css/adminlte.css',
                'resources/dist/css/adminlte.min.css',
                'resources/dist/js/pages/dashboard.js',
                'resources/dist/js/pages/dashboard2.js',
                'resources/dist/js/pages/dashboard3.js',
                'resources/dist/js/adminlte.js',
                'resources/dist/js/demo.js',
                'resources/plugins/fontawesome-free/css/all.min.css',
                'resources/plugins/summernote/summernote-bs5.css',
                'resources/plugins/summernote/summernote.css',
                'resources/plugins/overlayScrollbars/css/OverlayScrollbars.min.css',
                'resources/plugins/daterangepicker/daterangepicker.css',
                'resources/plugins/jquery/jquery.min.js',
                'resources/plugins/jquery-ui/jquery-ui.min.js',
                'resources/plugins/bootstrap/js/bootstrap.bundle.min.js',
                'resources/plugins/moment/moment.min.js',
                'resources/plugins/daterangepicker/daterangepicker.js',
                'resources/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js',
                'resources/plugins/summernote/summernote-bs5.js',
                'resources/plugins/summernote/summernote.js',
                'resources/plugins/bs-custom-file-input/bs-custom-file-input.min.js',
                'resources/dist/js/adminlte.js',
                'resources/dist/js/demo.js',
                'resources/dist/js/pages/dashboard.js',
            ],
            refresh: true,
        }),
    ],
});
